#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : opa-psm2
Version  : 10.2.260
Release  : 5
URL      : https://github.com/intel/opa-psm2/archive/PSM2_10.2-260.tar.gz
Source0  : https://github.com/intel/opa-psm2/archive/PSM2_10.2-260.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause Intel
Requires: opa-psm2-lib = %{version}-%{release}
Requires: opa-psm2-license = %{version}-%{release}
BuildRequires : numactl-dev

%description
This file is provided under a dual BSD/GPLv2 license.  When using or
redistributing this file, you may do so under either license.

%package dev
Summary: dev components for the opa-psm2 package.
Group: Development
Requires: opa-psm2-lib = %{version}-%{release}
Provides: opa-psm2-devel = %{version}-%{release}
Requires: opa-psm2 = %{version}-%{release}

%description dev
dev components for the opa-psm2 package.


%package lib
Summary: lib components for the opa-psm2 package.
Group: Libraries
Requires: opa-psm2-license = %{version}-%{release}

%description lib
lib components for the opa-psm2 package.


%package license
Summary: license components for the opa-psm2 package.
Group: Default

%description license
license components for the opa-psm2 package.


%prep
%setup -q -n opa-psm2-PSM2_10.2-260

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1565059532
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1565059532
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/opa-psm2
cp COPYING %{buildroot}/usr/share/package-licenses/opa-psm2/COPYING
cp debian/copyright %{buildroot}/usr/share/package-licenses/opa-psm2/debian_copyright
%make_install

%files
%defattr(-,root,root,-)
/lib/udev/rules.d/40-psm-compat.rules
/lib/udev/rules.d/40-psm.rules
/usr/lib/libpsm2/libpsm2-compat.cmds

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/hfi1diag/hfi1_deprecated.h
/usr/include/hfi1diag/linux-x86_64/bit_ops.h
/usr/include/hfi1diag/linux-x86_64/sysdep.h
/usr/include/hfi1diag/opa_byteorder.h
/usr/include/hfi1diag/opa_common.h
/usr/include/hfi1diag/opa_debug.h
/usr/include/hfi1diag/opa_intf.h
/usr/include/hfi1diag/opa_revision.h
/usr/include/hfi1diag/opa_service.h
/usr/include/hfi1diag/opa_udebug.h
/usr/include/hfi1diag/opa_user.h
/usr/include/hfi1diag/psm2_mock_testing.h
/usr/include/hfi1diag/psmi_wrappers.h
/usr/include/hfi1diag/ptl_ips/ipserror.h
/usr/lib64/libpsm2.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpsm2.so.2
/usr/lib64/libpsm2.so.2.1
/usr/lib64/psm2-compat/libpsm_infinipath.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/opa-psm2/COPYING
/usr/share/package-licenses/opa-psm2/debian_copyright
